Message:
  ti: "&b正在采集&c「&aITEM&c」&b中…"
  s0: "&b┠&f□-□-□-□-□-□-□-□-□&b┨"
  s1: "&b┠&f■-□-□-□-□-□-□-□-□&b┨"
  s2: "&b┠&f■-■-□-□-□-□-□-□-□&b┨"
  s3: "&b┠&f■-■-■-□-□-□-□-□-□&b┨"
  s4: "&b┠&f■-■-■-■-□-□-□-□-□&b┨"
  s5: "&b┠&f■-■-■-■-■-□-□-□-□&b┨"
  s6: "&b┠&f■-■-■-■-■-■-□-□-□&b┨"
  s7: "&b┠&f■-■-■-■-■-■-■-□-□&b┨"
  s8: "&b┠&f■-■-■-■-■-■-■-■-□&b┨"
  s9: "&b┠&f■-■-■-■-■-■-■-■-■&b┨"
MoreCollect: false
Power: 采集力
Speed: 采集效率